sudo: true
dist: xenial
language: go
services:
- docker
before_install:
- REPO=keptnexamples
- VERSION="$(cat version | tr -d '[:space:]')"
- echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
- REPO_URL="$(git remote get-url --all origin)"
- ./writeManifest.sh
- cat MANIFEST
jobs:
  include:
  - stage: workshop-utils-base
    env: IMAGE=keptnexamples/workshop-utils-base
    script:
    - echo $TRAVIS_BUILD_STAGE_NAME
    - docker build . -t "${IMAGE}:${VERSION}" -f Dockerfile_base
    - docker push "${IMAGE}:${VERSION}"
  - stage: workshop-utils-gke
    env: IMAGE=keptnexamples/workshop-utils-gke
    script:
    - echo $TRAVIS_BUILD_STAGE_NAME
    - docker build . -t "${IMAGE}:${VERSION}" -f Dockerfile_gke
    - docker push "${IMAGE}:${VERSION}"