sudo: true
dist: xenial
language: go
services:
- docker
before_install:
- REPO=keptnworkshops
- VERSION="$(cat version | tr -d '[:space:]')"
- echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
- REPO_URL="$(git remote get-url --all origin)"
- ./writeManifest.sh
- cat MANIFEST
jobs:
  include:
  - stage: build-and-push-all
    if: NOT type = pull_request
    script:
    - docker build . -t "${REPO}/workshop-utils-base:${VERSION}" -f Dockerfile_base
    - docker build . -t "${REPO}/workshop-utils-gke:${VERSION}" -f Dockerfile_base
    - docker build . -t "${REPO}/workshop-utils-eks:${VERSION}" -f Dockerfile_base
    - docker build . -t "${REPO}/workshop-utils-aks:${VERSION}" -f Dockerfile_base
    - docker build . -t "${REPO}/workshop-utils-ocp:${VERSION}" -f Dockerfile_base
    - docker build . -t "${REPO}/workshop-utils-pks:${VERSION}" -f Dockerfile_base
    - docker push "${REPO}/workshop-utils-base:${VERSION}"
    - docker push "${REPO}/workshop-utils-gke:${VERSION}"
    - docker push "${REPO}/workshop-utils-eks:${VERSION}"
    - docker push "${REPO}/workshop-utils-aks:${VERSION}"
    - docker push "${REPO}/workshop-utils-ocp:${VERSION}"
    - docker push "${REPO}/workshop-utils-pks:${VERSION}"