sudo: true
dist: xenial
language: go
services:
- docker
before_install:
- REPO=keptnworkshops
- echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
- REPO_URL="$(git remote get-url --all origin)"
- ./writeManifest.sh
- cat MANIFEST
jobs:
  include:
  - stage: workshop-utils-base
    env: IMAGE=keptnexamples/workshop-utils-base
    script:
    - echo $TRAVIS_BUILD_STAGE_NAME
    - docker build . -t "${IMAGE}:${TRAVIS_BRANCH}" -f Dockerfile_base
    - docker push "${IMAGE}:${TRAVIS_BRANCH}"
  - stage: workshop-utils-gke
    env: IMAGE=keptnexamples/workshop-utils-gke
    script:
    - echo $TRAVIS_BUILD_STAGE_NAME
    - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
    - docker build . -t "${IMAGE}:${TRAVIS_BRANCH}" -f Dockerfile_gke
    - docker push "${IMAGE}:${TRAVIS_BRANCH}"
  - stage: workshop-utils-eks
    env: IMAGE=keptnexamples/workshop-utils-eks
    script:
    - echo $TRAVIS_BUILD_STAGE_NAME
    - docker build . -t "${IMAGE}:${TRAVIS_BRANCH}" -f Dockerfile_eks
    - docker push "${IMAGE}:${TRAVIS_BRANCH}"
  - stage: workshop-utils-aks
    env: IMAGE=keptnexamples/workshop-utils-aks
    script:
    - echo $TRAVIS_BUILD_STAGE_NAME
    - docker build . -t "${IMAGE}:${TRAVIS_BRANCH}" -f Dockerfile_aks
    - docker push "${IMAGE}:${TRAVIS_BRANCH}"
  - stage: workshop-utils-ocp
    env: IMAGE=keptnexamples/workshop-utils-ocp
    script:
    - echo $TRAVIS_BUILD_STAGE_NAME
    - docker build . -t "${IMAGE}:${TRAVIS_BRANCH}" -f Dockerfile_ocp
    - docker push "${IMAGE}:${TRAVIS_BRANCH}"
  - stage: workshop-utils-pks
    env: IMAGE=keptnexamples/workshop-utils-pks
    script:
    - echo $TRAVIS_BUILD_STAGE_NAME
    - docker build . -t "${IMAGE}:${TRAVIS_BRANCH}" -f Dockerfile_pks
    - docker push "${IMAGE}:${TRAVIS_BRANCH}"