---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynatrace-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: dynatrace-service
  replicas: 1
  template:
    metadata:
      labels:
        run: dynatrace-service
    spec:
      containers:
      - name: dynatrace-service
        image: keptn/dynatrace-service:0.2.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: DT_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: dynatrace
              key: DT_API_TOKEN
        - name: DT_TENANT
          valueFrom:
            secretKeyRef:
              name: dynatrace
              key: DT_TENANT
---
apiVersion: v1
kind: Service
metadata:
  name: dynatrace-service
  namespace: keptn
  labels:
    run: dynatrace-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: dynatrace-service